### ISSUE TITLE
demo, time_to_batch: "TypeError: Expected int32"

### ISSUE THREAD

**Issue by drscotthawley** [tomlepaine/fast-wavenet#6]
Hey, would really love to try this out.    Here are a couple things I find when trying to run the demo...
(This is with tensorflow 0.10.0 on Mac OS X El Capitan, 10.11.6.)

```
Traceback (most recent call last):
  File "demo.py", line 15, in <module>
    from wavenet.models import Model, Generator
  File "/Users/myusername/exercises/neural/fast-wavenet/wavenet/models.py", line 4, in <module>
    from layers import (_causal_linear, _output_linear, conv1d,
ImportError: No module named 'layers'
```

If you change line 4 of models.py so it reads "from wavenet.layers" instead of just "from layers", then this error goes away.  That's easy.  

The next error, I don't know how to fix...

```
Traceback (most recent call last):
  File "demo.py", line 32, in <module>
    gpu_fraction=gpu_fraction)
  File "/Users/myusername/exercises/neural/fast-wavenet/wavenet/models.py", line 36, in __init__
    h = dilated_conv1d(h, num_hidden, rate=rate, name=name)
  File "/Users/myusername/exercises/neural/fast-wavenet/wavenet/layers.py", line 138, in dilated_conv1d
    inputs_ = time_to_batch(inputs, rate=rate)
  File "/Users/myusername/exercises/neural/fast-wavenet/wavenet/layers.py", line 26, in time_to_batch
    reshaped = tf.reshape(transposed, shape)
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/tensorflow/python/ops/gen_array_ops.py", line 1383, in reshape
    name=name)
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/tensorflow/python/ops/op_def_library.py", line 455, in apply_op
    as_ref=input_arg.is_ref)
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 620, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/tensorflow/python/ops/constant_op.py", line 179, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/tensorflow/python/ops/constant_op.py", line 162, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape))
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/tensorflow/python/framework/tensor_util.py", line 353, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/tensorflow/python/framework/tensor_util.py", line 290, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got 35316.0 of type 'float' instead.

```

How do we fix that?    I can see that right before the call to reshape,
transposed =  Tensor("b0-l0/transpose:0", shape=(35316, ?, 1), dtype=float32)

**Comment by tomlepaine** [comment]
Thanks for reporting this.

I'll fix the first error, and I'll try to recreate the second error now.

For context, are you using the most recent version of the repo?

**Comment by tomlepaine** [comment]
Also, I haven't tested this with python 3. Can you try python 2.7?

**Comment by drscotthawley** [comment]
Yes, I just started with the repo last night.

Ok, in python2.7 the errors do not appear.  This issue can be closed then.  

I'm curious where the python3 errors arise.   If I can find the problem, I'll fork and send you a pull request.

**Comment by tomlepaine** [comment]
Yeah, if you can track down that cause, let me know. Thanks!
