### ISSUE TITLE
Demo produces ValueError instantiating Model

### ISSUE THREAD

**Issue by mbaytas** [tomlepaine/fast-wavenet#8]
Using OS X 10.11.6, Python 2.7, tensorflow 0.9.0, the line

```
model = Model(num_time_samples=num_time_samples,
              num_channels=num_channels,
              gpu_fraction=gpu_fraction)
```

in the "demo" code produces the following error and fails:

```
Traceback (most recent call last):
  File "/fast-wavenet/demo.py", line 17, in <module>
    gpu_fraction=gpu_fraction)
  File "/fast-wavenet/wavenet/models.py", line 47, in __init__
    outputs, targets)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/nn_ops.py", line 454, in sparse_softmax_cross_entropy_with_logits
    logits, labels, name=name)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 1450, in _sparse_softmax_cross_entropy_with_logits
    features=features, labels=labels, name=name)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/op_def_library.py", line 704, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2262, in create_op
    set_shapes_for_outputs(ret)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1702, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/nn_ops.py", line 462, in _SparseSoftmaxCrossEntropyWithLogitsShape
    input_shape = logits_shape.with_rank(2)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/tensor_shape.py", line 641, in with_rank
    raise ValueError("Shape %s must have rank %d" % (self, rank))
ValueError: Shape (?, 35315, 256) must have rank 2
```

**Comment by dplaniel** [comment]
Using CentOS Linux 7.0.1406, Python 2.7, tensorflow 0.9.0, in Jupyter notebooks, I get the same error.

```
ValueError                                Traceback (most recent call last)
<ipython-input-2-fd2f697390fe> in <module>()
      6 model = Model(num_time_samples=num_time_samples,
      7               num_channels=num_channels,
----> 8               gpu_fraction=gpu_fraction)
      9 
     10 Audio(inputs.reshape(inputs.shape[1]), rate=44100)

/home/user/fast-wavenet/fast-wavenet/wavenet/models.pyc in __init__(self, num_time_samples, num_channels, num_classes, num_blocks, num_layers, num_hidden, gpu_fraction)
     45 
     46         costs = tf.nn.sparse_softmax_cross_entropy_with_logits(
---> 47             outputs, targets)
     48         cost = tf.reduce_mean(costs)
     49 

/opt/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/nn_ops.pyc in sparse_softmax_cross_entropy_with_logits(logits, labels, name)
    452   # _CrossEntropyGrad() in nn_grad but not here.
    453   cost, unused_backprop = gen_nn_ops._sparse_softmax_cross_entropy_with_logits(
--> 454       logits, labels, name=name)
    455   return cost
    456 

/opt/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/gen_nn_ops.pyc in _sparse_softmax_cross_entropy_with_logits(features, labels, name)
   1448   """
   1449   result = _op_def_lib.apply_op("SparseSoftmaxCrossEntropyWithLogits",
-> 1450                                 features=features, labels=labels, name=name)
   1451   return _SparseSoftmaxCrossEntropyWithLogitsOutput._make(result)
   1452 

/opt/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/op_def_library.pyc in apply_op(self, op_type_name, name, **keywords)
    702           op = g.create_op(op_type_name, inputs, output_types, name=scope,
    703                            input_types=input_types, attrs=attr_protos,
--> 704                            op_def=op_def)
    705           outputs = op.outputs
    706           return _Restructure(ops.convert_n_to_tensor(outputs),

/opt/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/ops.pyc in create_op(self, op_type, inputs, dtypes, input_types, name, attrs, op_def, compute_shapes, compute_device)
   2260                     original_op=self._default_original_op, op_def=op_def)
   2261     if compute_shapes:
-> 2262       set_shapes_for_outputs(ret)
   2263     self._add_op(ret)
   2264     self._record_op_seen_by_control_dependencies(ret)

/opt/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/ops.pyc in set_shapes_for_outputs(op)
   1700       raise RuntimeError("No shape function registered for standard op: %s"
   1701                          % op.type)
-> 1702   shapes = shape_func(op)
   1703   if shapes is None:
   1704     raise RuntimeError(

/opt/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/nn_ops.pyc in _SparseSoftmaxCrossEntropyWithLogitsShape(op)
    460   """Shape function for SparseSoftmaxCrossEntropyWithLogits op."""
    461   logits_shape = op.inputs[0].get_shape()
--> 462   input_shape = logits_shape.with_rank(2)
    463   batch_size = input_shape[0]
    464   # labels_shape

/opt/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/tensor_shape.pyc in with_rank(self, rank)
    639       return self.merge_with(unknown_shape(ndims=rank))
    640     except ValueError:
--> 641       raise ValueError("Shape %s must have rank %d" % (self, rank))
    642 
    643   def with_rank_at_least(self, rank):

ValueError: Shape (?, 35315, 256) must have rank 2
```

**Comment by AdrianLsk** [comment]
Hi, I resolved the issue by adjusting the cost (line 46) in `wavenet/models.py` as follows:

```
costs = tf.nn.sparse_softmax_cross_entropy_with_logits(
            tf.reshape(outputs, [-1, num_classes]), tf.reshape(targets, [-1]))
```
